# Generated by Django 4.1.1 on 2022-09-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='apellido',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='nombre',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
