# Generated by Django 4.1.1 on 2022-09-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_apellido_user_profile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='general_info',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
