# Generated by Django 4.1 on 2022-09-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_hotel_paquete_vuelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hoteles'},
        ),
    ]
