# Generated by Django 4.1 on 2022-09-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_delete_viajes_paquete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='viajes/'),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='viajes/'),
        ),
    ]
